// AUTOGENERATED FILE - DO NOT EDIT

var pt = window.PropTypes;
var pk = window['flash'];

pk.SSE.propTypes = {id:pt.string,
 setProps:pt.any,
 options:pt.shape({headers:pt.objectOf(pt.string),payload:pt.oneOfType([pt.string]),method:pt.string,withCredentials:pt.bool,start:pt.bool,debug:pt.bool}),
 url:pt.string,
 concat:pt.bool,
 animate_delay:pt.number,
 animate_chunk:pt.number,
 animate_prefix:pt.string,
 animate_suffix:pt.string,
 value:pt.string,
 animation:pt.string,
 done:pt.bool};
